services:
  - type: web
    name: smart-student-appointment
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app  # <-- Replace 'main' with your actual filename (without .py)
